/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error": "#690005",
        secondary: "#c6c6c7",
        "on-secondary-container": "#b4b5b5",
        "primary-fixed-dim": "#00e478",
        "tertiary-container": "#ffdb79",
        "terminal-black": "#000000",
        "on-surface-variant": "#b9cbb9",
        "surface-container-highest": "#2d372e",
        "tertiary-fixed": "#ffe08d",
        "surface-container": "#18221a",
        "on-tertiary-fixed-variant": "#584400",
        "inverse-on-surface": "#29332a",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#454747",
        "surface-bright": "#323c32",
        "warning-amber": "#FFB800",
        "on-tertiary": "#3d2f00",
        "surface-dim": "#0c160e",
        "tertiary-fixed-dim": "#e5c364",
        primary: "#f1ffef",
        error: "#ffb4ab",
        "secondary-fixed": "#e2e2e2",
        "surface-container-lowest": "#071009",
        background: "#0c160e",
        "surface-container-low": "#141e16",
        "on-primary-fixed-variant": "#005227",
        "primary-container": "#00ff87",
        "on-primary-fixed": "#00210c",
        "on-secondary": "#2f3131",
        tertiary: "#fffaf7",
        "metadata-gray": "#CCCCCC",
        "primary-fixed": "#60ff98",
        "on-secondary-fixed": "#1a1c1c",
        "on-background": "#dae6d8",
        "secondary-container": "#454747",
        "on-primary": "#003919",
        "surface-container-high": "#222c24",
        "on-primary-container": "#007138",
        "surface-variant": "#2d372e",
        "inverse-surface": "#dae6d8",
        "secondary-fixed-dim": "#c6c6c7",
        "on-tertiary-container": "#795f01",
        "on-tertiary-fixed": "#241a00",
        "grid-line": "rgba(0, 255, 135, 0.1)",
        outline: "#849585",
        "on-surface": "#dae6d8",
        "error-container": "#93000a",
        "inverse-primary": "#006d36",
        "outline-variant": "#3b4b3d",
        "surface-tint": "#00e478",
        surface: "#0c160e",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-edge": "40px",
        unit: "4px",
        "container-max": "1440px",
        gutter: "24px",
      },
      fontFamily: {
        "label-bilingual": ["JetBrains Mono", "monospace"],
        "headline-xl": ["Anybody", "sans-serif"],
        "body-main": ["JetBrains Mono", "monospace"],
        metadata: ["JetBrains Mono", "monospace"],
        "system-code": ["JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["Anybody", "sans-serif"],
        "headline-lg": ["Anybody", "sans-serif"],
      },
      fontSize: {
        "label-bilingual": ["12px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-xl": [
          "80px",
          { lineHeight: "1.0", letterSpacing: "-0.02em", fontWeight: "800" },
        ],
        "body-main": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        metadata: [
          "10px",
          { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "400" },
        ],
        "system-code": ["14px", { lineHeight: "1.5", fontWeight: "500" }],
        "headline-lg-mobile": [
          "32px",
          { lineHeight: "1.1", fontWeight: "700" },
        ],
        "headline-lg": ["48px", { lineHeight: "1.1", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
